version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # airflow:
  #   image: apache/airflow:2.7.2-python3.8
  #   container_name: airflow
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres_db/property_db
  #     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  #     AIRFLOW__WEBSERVER__RBAC: 'True'
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - airflow_data:/opt/airflow
  #     - ./dags:/opt/airflow/dags
  #   depends_on:
  #     - postgres
  #   command: >
  #     bash -c "airflow db migrate &&
  #              airflow users create --username admin2 --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
  #              airflow webserver & airflow scheduler"

volumes:
  # airflow_data:
  postgres_data:
